### ISSUE TITLE
Automatic chatlog creation when specific words are triggered

### ISSUE THREAD

**Issue by vainamov** [RewisServer/RewiMod#25]
_Included from the old RewiMod-project: https://github.com/AlexDigital/RewiMod/issues/4_

Users can create a blacklist for offending words. Whenever a word from the blacklist occurs in the chat, it triggers an automatic chatlog creation.

**Comment by k3kdude** [comment]
Arbeite dran!

**Comment by vainamov** [comment]
Done with commit https://github.com/RewisServer/RewiMod/commit/d2a259366c3c3537b92b996daafe7d0496dd3b45.

**Comment by ComputerBaer** [comment]
Kann der Benutzer die Wörter denn auch schon irgendwo eingeben?

**Comment by vainamov** [comment]
@ComputerBaer gehört das nicht in https://github.com/RewisServer/RewiMod/issues/45?
